### ISSUE TITLE
Intellij exception when doing find usage

### ISSUE THREAD

**Issue by bukajsytlos** [getgauge/Intellij-Plugin#116]
```
11:46:09 Throwable
         Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
         Details: Current thread: Thread[ApplicationImpl pooled thread 50,4,main] 1019114673
         ; dispatch thread: false; isDispatchThread(): false
         SystemEventQueueThread: Thread[AWT-EventQueue-0 IDEA 15.0.3#IU-143.1821.5 IDEA, eap:false, os:Linux 3.19.0-47-generic, java-version:Oracle Corporation 1.8.0_66-b17,6,main] 1986137279
```

```
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 50,4,main] 1019114673
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 IDEA 15.0.3#IU-143.1821.5 IDEA, eap:false, os:Linux 3.19.0-47-generic, java-version:Oracle Corporation 1.8.0_66-b17,6,main] 1986137279
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1055)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:178)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:794)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.getCanonicalText(PsiJavaCodeReferenceElementImpl.java:268)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.getCanonicalText(PsiJavaCodeReferenceElementImpl.java:259)
	at com.intellij.psi.impl.source.tree.java.PsiAnnotationImpl.getQualifiedName(PsiAnnotationImpl.java:96)
	at com.thoughtworks.gauge.util.StepUtil.isGaugeAnnotation(StepUtil.java:198)
	at com.thoughtworks.gauge.util.StepUtil.getGaugeStepAnnotationValues(StepUtil.java:178)
	at com.thoughtworks.gauge.util.StepUtil.getGaugeStepAnnotationValues(StepUtil.java:160)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.shouldFindUsages(ReferenceSearch.java:65)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.processQuery(ReferenceSearch.java:43)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.processQuery(ReferenceSearch.java:39)
	at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:79)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:45)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:66)
	at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:56)
	at com.intellij.find.findUsages.FindUsagesHandler.processElementUsages(FindUsagesHandler.java:126)
	at com.intellij.find.findUsages.FindUsagesManager$2.generate(FindUsagesManager.java:376)
	at com.intellij.usages.impl.SearchForUsagesRunnable.searchUsages(SearchForUsagesRunnable.java:346)
	at com.intellij.usages.impl.SearchForUsagesRunnable.run(SearchForUsagesRunnable.java:325)
	at com.intellij.usages.impl.UsageViewManagerImpl$1.run(UsageViewManagerImpl.java:131)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

**Comment by kashishm** [comment]
Could you please let us know what gauge-intelliJ plugin version you are using?

**Comment by bukajsytlos** [comment]
Sure. Version: 0.1.0

**Comment by kashishm** [comment]
Thanks for reporting the issue. We could not reproduce the issue on intelliJ 14 and intelliJ 15. 
The Following info might help us reproduce the issue: 
* What action/shortcut you used for find usages (alt+F7, cmd/ctrl+alt+F7)?
* Could you please try the same thing on a new Gauge project and let us know if you see the exception.

**Comment by bukajsytlos** [comment]
Hi. I used alt + f7 but I cannot reproduce it anymore. But it happend twice before I've reported it and as I can see there two more issues with same problem.
I didn't use gauge yet. Problem occurs on existing projects without any relation to gauge.

**Comment by kaustavdm** [comment]
Couldn't reproduce this on OSX El Capitan with IntelliJ IDEA 15 CE and Gauge plugin v0.1.0.

@bukajsytlos: Could you clarify what you meant by:

>  I didn't use gauge yet. Problem occurs on existing projects without any relation to gauge.

Sounds like it may be some IntelliJ issue on your end. Also, are you on Windows or OSX?

**Comment by bukajsytlos** [comment]
I mean i dont have installed gauge just intellij plugin (don't ask me why :D )
I have neither. As you can see in first log I use linux - kubuntu 14.04.3.
But as I stated I have exactly the same "issue" as https://github.com/getgauge/Intellij-Plugin/issues/118.
So I don't think its IDEAs issue.
