### ISSUE TITLE
read action exception

### ISSUE THREAD

**Issue by donnerpeter** [getgauge/Intellij-Plugin#118]
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 204,4,main] 293127616
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 15.0.2#IU-143.1183.10, eap:true,6,main] 847290744

java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1047)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:128)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
	at org.jetbrains.plugins.groovy.lang.psi.impl.InferenceContext$1.multiResolve(InferenceContext.java:69)
	at org.jetbrains.plugins.groovy.lang.psi.impl.types.GrCodeReferenceElementImpl.resolve(GrCodeReferenceElementImpl.java:123)
	at org.jetbrains.plugins.groovy.lang.psi.impl.auxiliary.annotation.GrAnnotationImpl.getQualifiedName(GrAnnotationImpl.java:102)
	at com.thoughtworks.gauge.util.StepUtil.isGaugeAnnotation(StepUtil.java:198)
	at com.thoughtworks.gauge.util.StepUtil.getGaugeStepAnnotationValues(StepUtil.java:178)
	at com.thoughtworks.gauge.util.StepUtil.getGaugeStepAnnotationValues(StepUtil.java:160)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.shouldFindUsages(ReferenceSearch.java:58)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.processQuery(ReferenceSearch.java:42)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.processQuery(ReferenceSearch.java:38)
	at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:79)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:45)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:66)
	at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:56)
	at com.intellij.psi.search.QuerySearchRequest.runQuery(QuerySearchRequest.java:58)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.appendCollectorsFromQueryRequests(PsiSearchHelperImpl.java:626)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processRequests(PsiSearchHelperImpl.java:587)
	at com.intellij.find.findUsages.FindUsagesManager$2.generate(FindUsagesManager.java:394)
	at com.intellij.usages.impl.SearchForUsagesRunnable.searchUsages(SearchForUsagesRunnable.java:346)
	at com.intellij.usages.impl.SearchForUsagesRunnable.run(SearchForUsagesRunnable.java:325)
	at com.intellij.usages.impl.UsageViewManagerImpl$1.run(UsageViewManagerImpl.java:131)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)

**Comment by sguptatw** [comment]
@kashishm : plz give the details/context about this bug.

**Comment by kashishm** [comment]
The issue was reported after updating Gauge IntelliJ plugin to [v0.1.0](https://github.com/getgauge/Intellij-Plugin/releases/tag/v0.1.0).
Users were seeing this exception when they were trying to use find usages feature on the existing Gauge projects(couldn't reproduce on new projects).
