### ISSUE TITLE
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())

### ISSUE THREAD

**Issue by vbauer** [getgauge/Intellij-Plugin#121]
Yesterday I got the following exception:

```
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 280,4,main] 70642491
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 IDEA 15.0.3#IU-143.1821.5 IDEA, eap:false, os:Mac OS X 10.11.3, java-version:JetBrains s.r.o 1.8.0_40-release-b119,6,main] 1440006175
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1055)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:178)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:794)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.getCanonicalText(PsiJavaCodeReferenceElementImpl.java:268)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.getCanonicalText(PsiJavaCodeReferenceElementImpl.java:259)
	at com.intellij.psi.impl.source.tree.java.PsiAnnotationImpl.getQualifiedName(PsiAnnotationImpl.java:96)
	at com.thoughtworks.gauge.util.StepUtil.isGaugeAnnotation(StepUtil.java:198)
	at com.thoughtworks.gauge.util.StepUtil.getGaugeStepAnnotationValues(StepUtil.java:178)
	at com.thoughtworks.gauge.util.StepUtil.getGaugeStepAnnotationValues(StepUtil.java:160)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.shouldFindUsages(ReferenceSearch.java:65)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.processQuery(ReferenceSearch.java:43)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.processQuery(ReferenceSearch.java:39)
	at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:79)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:45)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:66)
	at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:56)
	at com.intellij.find.findUsages.FindUsagesHandler.processElementUsages(FindUsagesHandler.java:126)
	at com.intellij.find.findUsages.FindUsagesManager$2.generate(FindUsagesManager.java:376)
	at com.intellij.usages.impl.SearchForUsagesRunnable.searchUsages(SearchForUsagesRunnable.java:346)
	at com.intellij.usages.impl.SearchForUsagesRunnable.run(SearchForUsagesRunnable.java:325)
	at com.intellij.usages.impl.UsageViewManagerImpl$1.run(UsageViewManagerImpl.java:131)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

Env:
* Intellij IDEA 15.0.3 Build IU-143.1821
* JRE 1.8.0._40 OpenJDK 64 bit
* OS X 10.11.3

**Comment by sguptatw** [comment]
@kashishm : plz add the details of this bug

**Comment by kashishm** [comment]
This issue is same as https://github.com/getgauge/Intellij-Plugin/issues/118
