### ISSUE TITLE
Getting an exception while removing a method implementation listed as safe to delete

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#131]
* Create a spec with a step
* Give an implementation to the step
* Use alt-enter to delete the new implementation. It says safe to delete. 
* On clicking the safe-delete the following exception occurs.
```
Access is allowed from event dispatch thread only.
 EventQueue.isDispatchThread()=false isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@9df555f Current thread: Thread[ApplicationImpl pooled thread 112,4,Idea Thread Group] 516971465 SystemEventQueueThread: Thread[AWT-EventQueue-0 2016.1#IC-145.258.11 IDEA, eap:false, os:Mac OS X 10.10.5, java-version:JetBrains s.r.o 1.8.0_40-release-b132,6,main] 740023282

java.lang.Throwable
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:501)
	at com.intellij.diagnostic.LogEventException.<init>(LogEventException.java:29)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1115)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1099)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1091)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:600)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:354)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:76)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:183)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.processQuery(ReferenceSearch.java:49)
	at com.thoughtworks.gauge.findUsages.ReferenceSearch.processQuery(ReferenceSearch.java:39)
	at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:79)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:45)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
	at com.intellij.util.MergeQuery.processSubQuery(MergeQuery.java:84)
	at com.intellij.util.MergeQuery.forEach(MergeQuery.java:56)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:66)
	at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:56)
	at com.intellij.util.UniqueResultsQuery.findAll(UniqueResultsQuery.java:78)
	at com.intellij.refactoring.safeDelete.JavaSafeDeleteProcessor.findMethodUsages(JavaSafeDeleteProcessor.java:606)
	at com.intellij.refactoring.safeDelete.JavaSafeDeleteProcessor.findUsages(JavaSafeDeleteProcessor.java:82)
	at org.jetbrains.kotlin.idea.refactoring.safeDelete.KotlinSafeDeleteProcessor.access$findUsages$s229615865(KotlinSafeDeleteProcessor.kt:53)
	at org.jetbrains.kotlin.idea.refactoring.safeDelete.KotlinSafeDeleteProcessor$findUsages$3.invoke(KotlinSafeDeleteProcessor.kt:73)
	at org.jetbrains.kotlin.idea.refactoring.safeDelete.KotlinSafeDeleteProcessor.findUsages(KotlinSafeDeleteProcessor.kt:211)
	at com.intellij.refactoring.safeDelete.SafeDeleteProcessor.findUsages(SafeDeleteProcessor.java:141)
	at com.intellij.refactoring.BaseRefactoringProcessor$1$1.compute(BaseRefactoringProcessor.java:166)
	at com.intellij.refactoring.BaseRefactoringProcessor$1$1.compute(BaseRefactoringProcessor.java:163)
	at com.intellij.openapi.project.DumbService$1.run(DumbService.java:89)
	at com.intellij.openapi.project.DumbService$2.compute(DumbService.java:125)
	at com.intellij.openapi.project.DumbService$2.compute(DumbService.java:119)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:966)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:119)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:86)
	at com.intellij.refactoring.BaseRefactoringProcessor$1.run(BaseRefactoringProcessor.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:227)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl$13$1.run(ApplicationImpl.java:633)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mahendrakariya** [comment]
Looks like this is related to #125. Fixing that issue may fix this as well.

**Comment by kashishm** [comment]
Fix will be available in nightly > 3/5/2016

**Comment by sguptatw** [comment]
Getting the safe delete for a step which has an implementation

Related Issues

- [ ] https://github.com/getgauge/Intellij-Plugin/issues/145
