### ISSUE TITLE
Null Pointer Exception while executing the spec

### ISSUE THREAD

**Issue by kashishm** [getgauge/Intellij-Plugin#133]
_From @sguptatw on April 11, 2016 8:54_

null
java.lang.NullPointerException
at com.thoughtworks.gauge.util.GaugeUtil.moduleDirPath(GaugeUtil.java:100)
at com.thoughtworks.gauge.util.GaugeUtil.moduleDir(GaugeUtil.java:96)
at com.thoughtworks.gauge.execution.GaugeRunConfiguration.addFlags(GaugeRunConfiguration.java:124)
at com.thoughtworks.gauge.execution.GaugeRunConfiguration.access$000(GaugeRunConfiguration.java:54)
at com.thoughtworks.gauge.execution.GaugeRunConfiguration$1.startProcess(GaugeRunConfiguration.java:97)
at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:80)
at com.intellij.execution.runners.DefaultProgramRunner.doExecute(DefaultProgramRunner.java:33)
at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
at com.intellij.execution.impl.ExecutionManagerImpl$5.run(ExecutionManagerImpl.java:389)
at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:161)
at com.intellij.execution.impl.ExecutionManagerImpl$4.run(ExecutionManagerImpl.java:346)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

### Expected behavior
Should be able to run without an exception

### Actual behavior
Getting a null pointer exception

### Steps to reproduce
1. Create a project with specs
2. Rename the project file
3. Execute the specs

### Gauge version
```
0.4.0
```

_Copied from original issue: getgauge/gauge#324_

**Comment by kashishm** [comment]
Fix will be available in nightly > 3/5/2016

**Comment by rabiamarzhiya** [comment]
Hi I am facing the null pointer exception while executing the spec file in gauge

Gauge version: 

Gauge version: 0.9.5
Commit Hash: 51cfe8d

Plugins
-------
html-report (4.0.2)
java (0.6.5)
js (2.0.0)
screenshot (0.0.1)
spectacle (0.1.2)

Gauge Plugin version: 0.3.8

Error stack trace:

Message: java.lang.NullPointerException
Stack Trace:
platform_e2e.PlatformObjects.userName(PlatformObjects.java:25)
platform_e2e.PlatformActions.login(PlatformActions.java:155)
platform_e2e.PlatformActions.loginSuccess(PlatformActions.java:142)
platform_e2e.registerSteps.loginValid(registerSteps.java:98)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
com.thoughtworks.gauge.execution.MethodExecutor.execute(MethodExecutor.java:38)
com.thoughtworks.gauge.execution.StepExecutionStage.executeStepMethod(StepExecutionStage.java:74)
com.thoughtworks.gauge.execution.StepExecutionStage.executeStep(StepExecutionStage.java:67)
com.thoughtworks.gauge.execution.StepExecutionStage.execute(StepExecutionStage.java:49)
com.thoughtworks.gauge.execution.AbstractExecutionStage.executeNext(AbstractExecutionStage.java:24)
com.thoughtworks.gauge.execution.HookExecutionStage.execute(HookExecutionStage.java:43)
com.thoughtworks.gauge.execution.ExecutionPipeline.start(ExecutionPipeline.java:29)
com.thoughtworks.gauge.processor.ExecuteStepProcessor.process(ExecuteStepProcessor.java:39)
com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:91)
com.thoughtworks.gauge.GaugeRuntime.dispatchMessages(GaugeRuntime.java:105)
com.thoughtworks.gauge.GaugeRuntime.access$100(GaugeRuntime.java:37)
com.thoughtworks.gauge.GaugeRuntime$2.run(GaugeRuntime.java:86)
java.lang.Thread.run(Thread.java:748).

Kindly help

**Comment by sskcar** [comment]
We still see the issue, I don't see a clear reason/details to fix either

**Comment by zabil** [comment]
Do you have a stack trace?
A null pointer error is something that can happen in your code. Gauge just reports it.
