### ISSUE TITLE
Exception in plugin on starting Intellij: cannot create class "com.thoughtworks.gauge.formatter.SpecFormatter"

### ISSUE THREAD

**Issue by kvelakur** [getgauge/Intellij-Plugin#176]
### Actual behavior
I see an exception in the Event Log when I open my multi module maven project using Intellij IDEA. The project does not open properly: none of the modules in my project are listed in the Project tree. After I disable the plugin everything works fine. 

`cannot create class "com.thoughtworks.gauge.formatter.SpecFormatter" [Plugin: com.thoughtworks.gauge]
com.intellij.diagnostic.PluginException: cannot create class "com.thoughtworks.gauge.formatter.SpecFormatter" [Plugin: com.thoughtworks.gauge]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:175)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:513)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:493)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:486)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.a(GotoActionItemProvider.java:197)
	at com.intellij.ide.util.gotoByName.GotoActionItemProvider.filterElements(GotoActionItemProvider.java:94)
	at com.intellij.ide.actions.SearchEverywhereAction$CalcThread.a(SearchEverywhereAction.java:1511)
	at com.intellij.ide.actions.SearchEverywhereAction$CalcThread.j(SearchEverywhereAction.java:1542)
	at com.intellij.ide.actions.SearchEverywhereAction$CalcThread.run(SearchEverywhereAction.java:1424)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
Caused by: com.intellij.diagnostic.PluginException: com/thoughtworks/gauge/formatter/SpecFormatter : Unsupported major.minor version 52.0 [Plugin: com.thoughtworks.gauge]
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:130)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:151)
	... 15 more
Caused by: java.lang.UnsupportedClassVersionError: com/thoughtworks/gauge/formatter/SpecFormatter : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:260)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:256)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:225)
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
	... 21 more
`

### Steps to reproduce
1. Create a multi module maven project.
2. Import to IDEA with gauge plugin enabled. 
3. Check Event Log. 

### Information that will help us debug

* IntelliJ version and edition(Community/Ultimate): 15.0.6 Ultimate
* OS information: Ubuntu 14.04 LTS
* Gauge IntelliJ plugin version: 0.2.1
* Does the project uses any Build tool(Gradle/Maven)? Maven
* Run gauge -v on your system and paste the results here. Not installed on my machine.

**Comment by mahendrakariya** [comment]
Is your Maven project a Gauge project?

**Comment by kvelakur** [comment]
Its not, I just had the plugin enabled. It used to work fine until recently.

**Comment by mahendrakariya** [comment]
This is a bug. Thanks for reporting this. We will look into it.

**Comment by kashishm** [comment]
I think you are using java7 on your machine. And the plugin is built using java8, that's why it is failing. If you can update java from 7 to 8 then it should work or update IntelliJ to the latest version will also fix the issue. This [post](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206103139-IntelliJ-Platform-migrates-to-Java-8) on IntelliJ forum has more details on this.

Fix in the plugin would be to change the value of `since-build` to 144.

**Comment by kashishm** [comment]
This was fixed in [0.2.3](https://github.com/getgauge/Intellij-Plugin/releases/tag/v0.2.3) release. The latest version of Gauge plugin supports IntelliJ 2016.* and above.
