### ISSUE TITLE
Should expand/collapse with inline data table as the parameter to the last step in the file

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#199]
**Expected behavior**
The entire content of the scenarios should be collapsed when the scenario is collapsed.

**Actual behavior**
The last line of the inline data table is not getting collapsed if the line is the eof.

**Steps to replicate**
1. Create a spec

```
Something
=========
Scenario Heading
----------------
tags: sdfsdf

* Step that takes a table1
* Concept Heading37a
* abcdefg "a" 

     |sfsdf|
     |-----|
     |a    |
```

Let the file end on the line ending on the inline table.
1. Expand and collapse to see the issue

**Version**
IntelliJ

```
gauge-java-intellij-0.2.4.nightly-2016-09-12
```

```
Gauge version: 0.6.2.nightly-2016-09-13

Plugins
-------
csharp (0.9.1.nightly-2016-08-12)
html-report (2.2.0.nightly-2016-08-28)
java (0.5.1.nightly-2016-09-09)
ruby (0.3.2.nightly-2016-08-22)
spectacle (0.0.1)
xml-report (0.1.4.nightly-2016-07-25)
```

**Comment by kashishm** [comment]
Fix will be available in nightly >= 2016-10-26

**Comment by sguptatw** [comment]
Getting an exception when I paste the above mentioned spec details in a new spec file

```
Invalid range specified: (20,19); 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:220)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:215)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:211)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:43)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:32)
	at com.thoughtworks.gauge.folding.GaugeFoldingBuilder.addNode(GaugeFoldingBuilder.java:19)
	at com.thoughtworks.gauge.folding.SpecFoldingBuilder.addNodes(SpecFoldingBuilder.java:27)
	at com.thoughtworks.gauge.folding.SpecFoldingBuilder.buildFoldRegions(SpecFoldingBuilder.java:19)
	at com.intellij.lang.folding.LanguageFolding.buildFoldingDescriptors(LanguageFolding.java:90)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:257)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getFoldingsFor(FoldingUpdate.java:243)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.getUpdateResult(FoldingUpdate.java:119)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.access$000(FoldingUpdate.java:55)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate$2.compute(FoldingUpdate.java:107)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate$2.compute(FoldingUpdate.java:102)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:53)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:43)
	at com.intellij.psi.util.CachedValuesManager.getParameterizedCachedValue(CachedValuesManager.java:97)
	at com.intellij.codeInsight.folding.impl.FoldingUpdate.updateFoldRegions(FoldingUpdate.java:101)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegions(CodeFoldingManagerImpl.java:345)
	at com.intellij.codeInsight.folding.impl.CodeFoldingManagerImpl.updateFoldRegionsAsync(CodeFoldingManagerImpl.java:327)
	at com.intellij.codeInsight.daemon.impl.CodeFoldingPass.doCollectInformation(CodeFoldingPass.java:42)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by kashishm** [comment]
Fix will be available in nightly >= 2016-12-19
