### ISSUE TITLE
Opening a report after execution is giving a null pointer exception

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#223]
**Expected behvaior**
I should be able to open the html-report from the IDE without a null pointer exception.

**Actual behavior**
```
update failed for AnAction with ID=RunClass
java.lang.NullPointerException
	at com.thoughtworks.gauge.execution.GaugeExecutionProducer.isInSpecScope(GaugeExecutionProducer.java:84)
	at com.thoughtworks.gauge.execution.GaugeExecutionProducer.isInSpecScope(GaugeExecutionProducer.java:84)
	at com.thoughtworks.gauge.execution.GaugeExecutionProducer.isInSpecScope(GaugeExecutionProducer.java:84)
	at com.thoughtworks.gauge.execution.GaugeExecutionProducer.isInSpecScope(GaugeExecutionProducer.java:84)
	at com.thoughtworks.gauge.execution.GaugeExecutionProducer.isInSpecScope(GaugeExecutionProducer.java:84)
	at com.thoughtworks.gauge.execution.GaugeExecutionProducer.isInSpecScope(GaugeExecutionProducer.java:84)
	at com.thoughtworks.gauge.execution.GaugeExecutionProducer.isInSpecScope(GaugeExecutionProducer.java:84)
	at com.thoughtworks.gauge.execution.GaugeExecutionProducer.isInSpecScope(GaugeExecutionProducer.java:84)
	at com.thoughtworks.gauge.execution.GaugeExecutionProducer.isInSpecScope(GaugeExecutionProducer.java:84)
	at com.thoughtworks.gauge.execution.GaugeExecutionProducer.isInSpecScope(GaugeExecutionProducer.java:84)
	at com.thoughtworks.gauge.execution.GaugeExecutionProducer.isInSpecScope(GaugeExecutionProducer.java:84)
	at com.thoughtworks.gauge.execution.GaugeExecutionProducer.isConfigurationFromContext(GaugeExecutionProducer.java:76)
	at com.intellij.execution.actions.RunConfigurationProducer.findExistingConfiguration(RunConfigurationProducer.java:220)
	at com.intellij.execution.actions.ConfigurationContext.findExisting(ConfigurationContext.java:214)
	at com.intellij.execution.actions.BaseRunConfigurationAction.update(BaseRunConfigurationAction.java:191)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:120)
	at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:188)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:139)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:164)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:164)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:164)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:164)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:86)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:280)
	at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.show(ActionPopupMenuImpl.java:95)
	at com.intellij.ide.ui.customization.CustomizationUtil$3.invokePopup(CustomizationUtil.java:291)
	at com.intellij.ui.PopupHandler.mousePressed(PopupHandler.java:48)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6530)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:410)
	at com.intellij.ide.dnd.aware.DnDAwareTree.processMouseEvent(DnDAwareTree.java:58)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
**Steps to replicate**
* Create a spec
```
Specification Heading
=====================
Scenario Heading
----------------
* Refactor step "Step with \<a\> \<b\>" to "Step having \<b\> and \<a\>" via api
```
* Give default implementation to the step. resolve the code issue of parameter mismatch manually.
* Run the spec
* Try opening the html-report from the IDE. The above exception occurs

**Version**
```
Gauge version: 0.7.1.nightly-2017-01-06

Plugins
-------
html-report (3.0.1.nightly-2017-01-10)
java (0.5.2.nightly-2016-12-20)
ruby (0.3.1)
```

**Comment by kashishm** [comment]
Fix will be available in nightly >= 0.2.6.nightly-2017-01-13
