### ISSUE TITLE
Unable to find Gauge in Path

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#236]
**Expected behavior**
If Gauge is executing from command line, I should be able to execute it from IDE.

**Actual behavior**
Unable to find Gauge in Path
```
Could not start gauge api: Could not find executable in PATH or GAUGE_ROOT. Gauge is not installed.: Could not find executable in PATH or GAUGE_ROOT. Gauge is not installed.
com.thoughtworks.gauge.exception.GaugeNotFoundException: Could not find executable in PATH or GAUGE_ROOT. Gauge is not installed.
	at com.thoughtworks.gauge.util.GaugeUtil.getPath(GaugeUtil.java:80)
	at com.thoughtworks.gauge.util.GaugeUtil.getGaugeExecPath(GaugeUtil.java:50)
	at com.thoughtworks.gauge.GaugeModuleComponent.initializeGaugeProcess(GaugeModuleComponent.java:122)
	at com.thoughtworks.gauge.GaugeModuleComponent.createGaugeService(GaugeModuleComponent.java:105)
	at com.thoughtworks.gauge.module.lib.AbstractLibHelper.<init>(AbstractLibHelper.java:37)
	at com.thoughtworks.gauge.module.lib.LibHelperFactory$GaugeModuleLibHelper.<init>(LibHelperFactory.java:43)
	at com.thoughtworks.gauge.module.lib.LibHelperFactory.helperFor(LibHelperFactory.java:33)
	at com.thoughtworks.gauge.GaugeModuleComponent.projectOpened(GaugeModuleComponent.java:79)
	at com.thoughtworks.gauge.GaugeModuleComponent.moduleAdded(GaugeModuleComponent.java:94)
	at com.intellij.openapi.module.impl.ModuleImpl.moduleAdded(ModuleImpl.java:208)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.lambda$fireModuleAddedInWriteAction$5(ModuleManagerImpl.java:570)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:934)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.fireModuleAddedInWriteAction(ModuleManagerImpl.java:569)
	at com.intellij.openapi.module.impl.ModuleManagerComponent.lambda$fireModulesAdded$0(ModuleManagerComponent.java:124)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:91)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:159)
	at com.intellij.openapi.module.impl.ModuleManagerComponent.fireModulesAdded(ModuleManagerComponent.java:124)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.projectOpened(ModuleManagerImpl.java:557)
	at com.intellij.openapi.project.impl.ProjectImpl.projectOpened(ProjectImpl.java:390)
	at com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:70)
	at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectOpened(ProjectImpl.java:425)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$1.projectOpened(ProjectManagerImpl.java:91)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.fireProjectOpened(ProjectManagerImpl.java:657)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$null$4(ProjectManagerImpl.java:329)
	at com.intellij.openapi.application.TransactionGuardImpl$3.run(TransactionGuardImpl.java:173)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:91)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:41)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:116)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:930)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:207)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:435)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:76)
	at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:338)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runSynchronously(CoreProgressManager.java:342)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:321)
	at com.intellij.openapi.progress.ProgressManager.run(ProgressManager.java:197)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:403)
	at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:189)
	at com.intellij.ide.RecentProjectsManagerImpl.doOpenProject(RecentProjectsManagerImpl.java:60)
	at com.intellij.ide.ReopenProjectAction.actionPerformed(ReopenProjectAction.java:68)
	at com.intellij.openapi.wm.impl.welcomeScreen.RecentProjectPanel$2.onClick(RecentProjectPanel.java:126)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:73)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at com.intellij.openapi.wm.impl.welcomeScreen.RecentProjectPanel$MyList.processMouseEvent(RecentProjectPanel.java:347)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:675)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
**Steps to replicate**
* Install in custom path /tmp using the zip file option.
* Now install using the pkg option.
* Now open the IntelliJ IDE and getting the above error.

> Note: Further info
```
$ echo $GAUGE_ROOT
/Users/<username>/.gauge/config
$ which gauge
/usr/local/bin/gauge
```

> Note: This works as expected from the command line.

**Comment by sguptatw** [comment]
Deleted the `/Users/sswaroop/.gauge/` folder installed the latest java and html-report nightlies. 
```
gauge -v
Gauge version: 0.8.2.nightly-2017-03-17

Plugins
-------
html-report (3.1.0.nightly-2017-02-20)
java (0.6.2.nightly-2017-03-16)
```
IntelliJ version is `0.3.1`

**Comment by kashishm** [comment]
We have changed the order for Gauge executable search in IntelliJ plugin.

1. `GAUGE_HOME`
2. `PATH`
3. `GAUGE_ROOT` # for backward compatibility

If a user has installed Gauge to a custom location, the Gauge installers will add the custom location to `PATH` in  `~/.profile`. This will work in console but IntelliJ won't get this updated PATH.

For this, Linux/Mac zip/pkg installers will have to add a symlink in `$HOME/bin/gauge` which will refer to gauge's custom location executable. And IntelliJ will use symlink in `GAUGE_HOME` if present otherwise it will continue the search in `PATH` and `GAUGE_ROOT`.

**Comment by kashishm** [comment]
The other solution could be to add a Gauge plugin config/settings in IntelliJ to specify `gauge` executable path. By default, it can be set to the default location but the user can override/edit it.

**Comment by sguptatw** [comment]
I am not getting the exception anymore. However I am getting the following error when I run the specs
```
/usr/local/bin/gauge --simple-console /Users/<username>/work/performance/gaugeTest/art/specs/example2.spec
2017/03/21 17:11:03 Failed to get configuration from Gauge properties file. Error: open /Users/<username>/.gauge/config/gauge.properties: no such file or directory
2017/03/21 17:11:03 Incorrect value for check_updates in property file. Cannot convert  to boolean.
2017/03/21 17:11:03 Failed to get configuration from Gauge properties file. Error: open /Users/<username>/.gauge/config/gauge.properties: no such file or directory
2017/03/21 17:11:03 Failed to get configuration from Gauge properties file. Error: open /Users/<username>/.gauge/config/gauge.properties: no such file or directory
2017/03/21 17:11:03 Failed to get configuration from Gauge properties file. Error: open /Users/<username>/.gauge/config/gauge.properties: no such file or directory
2017/03/21 17:11:03 Failed to get configuration from Gauge properties file. Error: open /Users/<username>/.gauge/config/gauge.properties: no such file or directory
2017/03/21 17:11:03 Incorrect value for runner_connection_timeout in property file. Cannot convert  to time
2017/03/21 17:11:03 Failed to get configuration from Gauge properties file. Error: open /Users/<username>/.gauge/config/gauge.properties: no such file or directory
2017/03/21 17:11:03 Incorrect value for runner_request_timeout in property file. Cannot convert  to time
2017/03/21 17:11:06 Failed to get configuration from Gauge properties file. Error: open /Users/<username>/.gauge/config/gauge.properties: no such file or directory
2017/03/21 17:11:06 Incorrect value for runner_request_timeout in property file. Cannot convert  to time
2017/03/21 17:11:09 Failed to get configuration from Gauge properties file. Error: open /Users/<username>/.gauge/config/gauge.properties: no such file or directory
2017/03/21 17:11:09 Incorrect value for runner_request_timeout in property file. Cannot convert  to time
[ValidationError] /Users/<username>/work/performance/gaugeTest/art/specs/example2.spec:7 Request Timeout => 'Open the Gauge homepage'
[ValidationError] /Users/<username>/work/performance/gaugeTest/art/specs/example2.spec:11 Request Timeout => 'Go to Gauge Get Started Page'
[ValidationError] /Users/<username>/work/performance/gaugeTest/art/specs/example2.spec:12 Request Timeout => 'Ensure installation instructions are available'
[ValidationError] /Users/<username>/work/performance/gaugeTest/art/specs/example2.spec:16 Request Timeout => 'Go to Gauge Get Started Page'
[ValidationError] /Users/<username>/work/performance/gaugeTest/art/specs/example2.spec:17 Request Timeout => 'Ensure installation instructions are available'
[ValidationError] /Users/<username>/work/performance/gaugeTest/art/specs/example2.spec:21 Request Timeout => 'Go to Gauge Get Started Page'
[ValidationError] /Users/<username>/work/performance/gaugeTest/art/specs/example2.spec:22 Request Timeout => 'Ensure installation instructions are available'
[ValidationError] /Users/<username>/work/performance/gaugeTest/art/specs/example2.spec:26 Request Timeout => 'Go to Gauge Get Started Page'
[ValidationError] /Users/<username>/work/performance/gaugeTest/art/specs/example2.spec:27 Request Timeout => 'Ensure installation instructions are available'
[ValidationError] /Users/<username>/work/performance/gaugeTest/art/specs/example2.spec:31 Request Timeout => 'Go to Gauge Get Started Page'
[ValidationError] /Users/<username>/work/performance/gaugeTest/art/specs/example2.spec:32 Request Timeout => 'Ensure installation instructions are available'
[ValidationError] /Users/<username>/work/performance/gaugeTest/art/specs/example2.spec:36 Request Timeout => 'Go to Gauge Get Started Page'
[ValidationError] /Users/<username>/work/performance/gaugeTest/art/specs/example2.spec:37 Request Timeout => 'Ensure installation instructions are available'
[ValidationError] /Users/<username>/work/performance/gaugeTest/art/specs/example2.spec:41 Request Timeout => 'Go to Gauge Get Started Page'
[ValidationError] /Users/<username>/wo
```

**Comment by kashishm** [comment]
@sguptatw Could you please update gauge=0.8.3, gauge-java=0.6.2 and Gauge IntelliJ plugin=0.3.3 and then try
