### ISSUE TITLE
Getting an exception while giving a path location in the spec file.

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#247]
**Expected behavior**
I should be able to work seamlessly while writing a spec

**Actual behavior**
Getting an exception while giving a path location in the spec file.
```
Illegal Unicode escape sequence near index 32
Login with user details <specs\userDetails.csv> t
                                ^
java.util.regex.PatternSyntaxException: Illegal Unicode escape sequence near index 32
Login with user details <specs\userDetails.csv> t
                                ^
	at java.util.regex.Pattern.error(Pattern.java:1955)
	at java.util.regex.Pattern.uxxxx(Pattern.java:3235)
	at java.util.regex.Pattern.u(Pattern.java:3243)
	at java.util.regex.Pattern.escape(Pattern.java:2441)
	at java.util.regex.Pattern.atom(Pattern.java:2198)
	at java.util.regex.Pattern.sequence(Pattern.java:2130)
	at java.util.regex.Pattern.expr(Pattern.java:1996)
	at java.util.regex.Pattern.compile(Pattern.java:1696)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1054)
	at com.thoughtworks.gauge.autocomplete.GaugePrefixMatcher.<init>(GaugePrefixMatcher.java:15)
	at com.thoughtworks.gauge.autocomplete.StepCompletionProvider.addCompletions(StepCompletionProvider.java:66)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:773)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$500(CompletionProgressIndicator.java:91)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:755)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:87)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$1(CompletionThreading.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$2(CompletionThreading.java:82)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.util.regex.PatternSyntaxException: Illegal Unicode escape sequence near index 32
Login with user details <specs\userDetails.csv> to
                                ^
	at java.util.regex.Pattern.error(Pattern.java:1955)
	at java.util.regex.Pattern.uxxxx(Pattern.java:3235)
	at java.util.regex.Pattern.u(Pattern.java:3243)
	at java.util.regex.Pattern.escape(Pattern.java:2441)
	at java.util.regex.Pattern.atom(Pattern.java:2198)
	at java.util.regex.Pattern.sequence(Pattern.java:2130)
	at java.util.regex.Pattern.expr(Pattern.java:1996)
	at java.util.regex.Pattern.compile(Pattern.java:1696)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1054)
	at com.thoughtworks.gauge.autocomplete.GaugePrefixMatcher.<init>(GaugePrefixMatcher.java:15)
	at com.thoughtworks.gauge.autocomplete.StepCompletionProvider.addCompletions(StepCompletionProvider.java:66)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:773)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$500(CompletionProgressIndicator.java:91)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:755)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:87)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$1(CompletionThreading.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$2(CompletionThreading.java:82)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
**Steps to replicate**
* Create a new project
* Start typing the following text
`Login with user details <specs/userDetails.csv>`
* Now change `/u` to `\u`
This is when I got the exception

**Version**
```
Gauge version: 0.8.4.nightly-2017-04-26

Plugins
-------
html-report (4.0.0.nightly-2017-04-26)
java (0.6.3.nightly-2017-04-21)
xml-report (0.2.0)
```

**Comment by sguptatw** [comment]
Working as expected in
```
Gauge version: 1.0.1.nightly-2018-07-31
Commit Hash: 4ae7c9a

Plugins
-------
html-report (4.0.5.nightly-2018-07-25)
java (0.6.9.nightly-2018-06-29)
```
