### ISSUE TITLE
Gauge Plugin fails with latest Intellij version

### ISSUE THREAD

**Issue by nehashri** [getgauge/Intellij-Plugin#278]
Opening any project(not necessarily a gauge project) with latest Intellij version(2017.2) fails if gauge plugin is installed on the machine before update.

Stacktrace of error:
@NotNull method com/intellij/openapi/module/impl/ModuleImpl.getOptionManager must not return null
java.lang.IllegalStateException: @NotNull method com/intellij/openapi/module/impl/ModuleImpl.getOptionManager must not return null
	at com.intellij.openapi.module.impl.ModuleImpl.a(ModuleImpl.java:235)
	at com.intellij.openapi.module.impl.ModuleImpl.getOptionValue(ModuleImpl.java:240)
	at com.thoughtworks.gauge.core.Gauge.getProjectGroupValue(Gauge.java:90)
	at com.thoughtworks.gauge.core.Gauge.disposeComponent(Gauge.java:101)
	at com.thoughtworks.gauge.GaugeModuleComponent.disposeComponent(GaugeModuleComponent.java:61)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.disposeComponents(ComponentManagerImpl.java:149)
	at com.intellij.openapi.module.impl.ModuleImpl.dispose(ModuleImpl.java:156)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:48)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:138)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:151)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:137)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:125)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:121)
	at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.a(ModuleManagerImpl.java:857)
	at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.access$100(ModuleManagerImpl.java:598)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.dispose(ModuleManagerImpl.java:126)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:48)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:138)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:151)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:126)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:151)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:137)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:125)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:121)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:679)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1031)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:673)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeAndDispose(ProjectManagerImpl.java:697)
	at com.intellij.ide.impl.ProjectUtil.closeAndDispose(ProjectUtil.java:91)
	at com.intellij.openapi.wm.impl.IdeFrameImpl$1.windowClosing(IdeFrameImpl.java:193)
	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
	at java.awt.Window.processWindowEvent(Window.java:2054)
	at javax.swing.JFrame.processWindowEvent(JFrame.java:305)
	at java.awt.Window.processEvent(Window.java:2013)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by BugDiver** [comment]
Fix should be available in nightly >= 20-7-2017

**Comment by nehashri** [comment]
Still reproducible, happens when opening a gradle java project. (Not a gauge project).

**Comment by jtonic** [comment]
Hi. 
For me this is still reproducible for a kotlin maven project with a newer nightly gauge plugin.

**Comment by kashishm** [comment]
@jtonic Please try with the latest nightly(26-7-2017).

**Comment by koppor** [comment]
Gauge Version 0.3.4 used at a Gradle project. Happened after clicking "OK" at the question whether non-existing gradle modules should be removed.

```
@NotNull method com/intellij/openapi/module/impl/ModuleImpl.getOptionManager must not return null
java.lang.IllegalStateException: @NotNull method com/intellij/openapi/module/impl/ModuleImpl.getOptionManager must not return null
	at com.intellij.openapi.module.impl.ModuleImpl.d(ModuleImpl.java)
	at com.intellij.openapi.module.impl.ModuleImpl.a(ModuleImpl.java:226)
```

<details>

```
@NotNull method com/intellij/openapi/module/impl/ModuleImpl.getOptionManager must not return null
java.lang.IllegalStateException: @NotNull method com/intellij/openapi/module/impl/ModuleImpl.getOptionManager must not return null
	at com.intellij.openapi.module.impl.ModuleImpl.d(ModuleImpl.java)
	at com.intellij.openapi.module.impl.ModuleImpl.a(ModuleImpl.java:226)
	at com.intellij.openapi.module.impl.ModuleImpl.getOptionValue(ModuleImpl.java:231)
	at com.thoughtworks.gauge.core.Gauge.getProjectGroupValue(Gauge.java:90)
	at com.thoughtworks.gauge.core.Gauge.disposeComponent(Gauge.java:101)
	at com.thoughtworks.gauge.GaugeModuleComponent.disposeComponent(GaugeModuleComponent.java:64)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.disposeComponents(ComponentManagerImpl.java:149)
	at com.intellij.openapi.module.impl.ModuleImpl.dispose(ModuleImpl.java:147)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:48)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:138)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:167)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:142)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:129)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:125)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.a(ModuleManagerImpl.java:968)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.makeRootsChange(ProjectRootManagerImpl.java:333)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.a(ModuleManagerImpl.java:928)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.access$1400(ModuleManagerImpl.java:75)
	at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.a(ModuleManagerImpl.java:838)
	at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.access$1200(ModuleManagerImpl.java:618)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.commitModelWithRunnable(ModuleManagerImpl.java:609)
	at com.intellij.openapi.roots.impl.ModifiableModelCommitter.multiCommit(ModifiableModelCommitter.java:50)
	at com.intellij.openapi.roots.impl.ModifiableModelCommitter.multiCommit(ModifiableModelCommitter.java:39)
	at com.intellij.openapi.externalSystem.service.project.AbstractIdeModifiableModelsProvider.b(AbstractIdeModifiableModelsProvider.java:431)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.mergeRootsChangesDuring(ProjectRootManagerImpl.java:298)
	at com.intellij.openapi.externalSystem.service.project.AbstractIdeModifiableModelsProvider.commit(AbstractIdeModifiableModelsProvider.java:414)
	at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManagerImpl$2.execute(ProjectDataManagerImpl.java:432)
	at com.intellij.openapi.externalSystem.util.DisposeAwareProjectChange.run(DisposeAwareProjectChange.java:36)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1003)
	at com.intellij.openapi.externalSystem.util.ExternalSystemApiUtil.lambda$executeProjectChangeAction$6(ExternalSystemApiUtil.java:457)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:158)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.h(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


</details>

**Comment by BugDiver** [comment]
@koppor  looks like you are using an old version of gauge-plugin.
please try with the latest gauge, IntelliJ plugin, and Gradle plugin.

**Comment by eyalgo** [comment]
Hi,
I am using the latest Gradle plugin.
The JDK is 1.8.0_152 (the bundled from IntelliJ). (made sure in _Switch Boot JDK_ option)
IntelliJ: 2018.1.4 Build #UI-181.5087.20
(see screenshot)
![screen shot 2018-05-31 at 09 00 45](https://user-images.githubusercontent.com/1395180/40767066-b26efa02-64b1-11e8-9875-fe5e9c90b7ca.png)

Still getting:
`Argument for @NotNull parameter 'quickFixes' of com/intellij/openapi/externalSystem/service/execution/ExternalSystemJdkException.<init> must not be null`

Any idea what else can I do?

Thanks !

**Comment by nehashri** [comment]
@eyalgo What is the issue you are facing? Are you using `Gauge` plugin? This is a Gauge forum, not Gradle's.

**Comment by eyalgo** [comment]
just noticed. sorry about that :)
I get the same error message, but it's probably because of the gradle plugin.
I don't use the Gauge plugin.

Thanks anyway (and sorry)
