### ISSUE TITLE
Support IntelliJ 2018.2

### ISSUE THREAD

**Issue by rgoldberg** [getgauge/Intellij-Plugin#339]
Support IntelliJ 2018.2, which is currently in beta, and will be released not too long from now.

Presumably, `customUntilBuild` must be set to `182.*`, and the Gauge plugin must conform to any IntelliJ API changes.

https://github.com/getgauge/Intellij-Plugin/blob/bc0c60d210e3e614d9c9b664e6a51999dbaf54a5/gradle.properties#L3

**Comment by NivedhaSenthil** [comment]
Thanks for the heads up, will be great if you can create a PR meanwhile.

**Comment by rgoldberg** [comment]
I don’t know what changes need to be implemented, so it’s probably safer if it’s done by someone who’s familiar with the Guage plugin code.

**Comment by DaSwedishMan** [comment]
Any update on this topic? IntelliJ 2018.2 was just released.

**Comment by rgoldberg** [comment]
IntelliJ keeps telling me to downgrade to 0.3.4 of the plugin (presumably because 0.3.4 doesn't have an upper bound on the supported IntelliJ version).  I imagine that 0.3.4 is even less likely than the current version (0.3.11) to work with 2018.2.  If that's so, there's no reason for people to install an older, less compatible version of this plugin than a newer one that probably has fewer inconsistencies with a newer IntelliJ.  If 0.3.4 will actually work with 2018.2 better than any subsequent releases of the plugin, can you explain why that's so?

If 0.3.4 is worse indeed less compatible with newer IntelliJ than later versions, can you just remove the upper bound on the version of IntelliJ that the plugin works with?

**Comment by nehashri** [comment]
Needs to be reviewed by QA

**Comment by sguptatw** [comment]
Getting the following error on opening the project https://github.com/getgauge-examples/ioc-spring.git
```
java.lang.IllegalStateException: @NotNull method com/intellij/openapi/module/impl/ModuleImpl.getOptionManager must not return null
	at com.intellij.openapi.module.impl.ModuleImpl.$$$reportNull$$$0(ModuleImpl.java)
	at com.intellij.openapi.module.impl.ModuleImpl.getOptionManager(ModuleImpl.java:224)
	at com.intellij.openapi.module.impl.ModuleImpl.getOptionValue(ModuleImpl.java:229)
	at com.thoughtworks.gauge.core.Gauge.getProjectGroupValue(Gauge.java:90)
	at com.thoughtworks.gauge.core.Gauge.disposeComponent(Gauge.java:101)
	at com.thoughtworks.gauge.GaugeModuleComponent.disposeComponent(GaugeModuleComponent.java:64)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.disposeComponents(ComponentManagerImpl.java:136)
	at com.intellij.openapi.module.impl.ModuleImpl.dispose(ModuleImpl.java:145)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:48)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:138)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:182)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:151)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:129)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:125)
	at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.disposeModel(ModuleManagerImpl.java:915)
	at com.intellij.openapi.module.impl.ModuleManagerImpl$ModuleModelImpl.access$100(ModuleManagerImpl.java:639)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.dispose(ModuleManagerImpl.java:115)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:48)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:138)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:182)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:126)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:182)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:151)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:129)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:125)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$closeProject$15(ProjectManagerImpl.java:689)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1028)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeProject(ProjectManagerImpl.java:683)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeAndDispose(ProjectManagerImpl.java:707)
	at com.intellij.ide.impl.ProjectUtil.closeAndDispose(ProjectUtil.java:91)
	at com.intellij.openapi.wm.impl.IdeFrameImpl$3.windowClosing(IdeFrameImpl.java:269)
	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
	at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
	at java.awt.Window.processWindowEvent(Window.java:2054)
	at javax.swing.JFrame.processWindowEvent(JFrame.java:305)
	at java.awt.Window.processEvent(Window.java:2013)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by nehashri** [comment]
New version of IntelliJ 0.3.12 is now released. It should work with IntelliJ 2018.2.
Please update your plugin and check
