### ISSUE TITLE
Execution produces exception

### ISSUE THREAD

**Issue by BugDiver** [getgauge/Intellij-Plugin#349]
### Expected behavior
Execution should work without exception.

### Actual behavior
When a spec is executed using the run config it produces and exception

Stacktrace:
```
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$5.invoke(ProcessHandler.java:223)
	at com.sun.proxy.$Proxy17.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:197)
	at com.intellij.execution.process.ColoredProcessHandler.textAvailable(ColoredProcessHandler.java:96)
	at com.intellij.execution.process.ColoredProcessHandler.coloredTextAvailable(ColoredProcessHandler.java:71)
	at com.intellij.execution.process.AnsiEscapeDecoder.processTextChunk(AnsiEscapeDecoder.java:267)
	at com.intellij.execution.process.AnsiEscapeDecoder.escapeText(AnsiEscapeDecoder.java:67)
	at com.intellij.execution.process.ColoredProcessHandler.notifyTextAvailable(ColoredProcessHandler.java:60)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:198)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:202)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:186)
	at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:105)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:85)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:163)
	at com.intellij.util.io.BaseDataReader$1$1.run(BaseDataReader.java:66)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.util.io.BaseDataReader$1.run(BaseDataReader.java:63)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.thoughtworks.gauge.execution.runner.processors.SuiteEventProcessor.canProcess(SuiteEventProcessor.java:30)
	at com.thoughtworks.gauge.execution.runner.GaugeOutputToGeneralTestEventsProcessor.processServiceMessages(GaugeOutputToGeneralTestEventsProcessor.java:55)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.processConsistentText(OutputToGeneralTestEventsConverter.java:100)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter$1.onLineAvailable(OutputToGeneralTestEventsConverter.java:54)
	at com.intellij.execution.testframework.sm.runner.OutputLineSplitter.onChunksAvailable(OutputLineSplitter.java:173)
	at com.intellij.execution.testframework.sm.runner.OutputLineSplitter.flushStdOutBuffer(OutputLineSplitter.java:150)
	at com.intellij.execution.testframework.sm.runner.OutputLineSplitter.processStdOutConsistently(OutputLineSplitter.java:105)
	at com.intellij.execution.testframework.sm.runner.OutputLineSplitter.processLine(OutputLineSplitter.java:70)
	at com.intellij.execution.testframework.sm.runner.OutputLineSplitter.process(OutputLineSplitter.java:53)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.process(OutputToGeneralTestEventsConverter.java:72)
	at com.intellij.execution.testframework.sm.SMTestRunnerConnectionUtil$2.onTextAvailable(SMTestRunnerConnectionUtil.java:211)
```

### Version information

* IntelliJ version and edition(Community/Ultimate): 2018.2 CE
* OS information: OSx
* Gauge IntelliJ plugin version:  0.3.13.nightly-2018-08-08
* Does the project uses any Build tool(Gradle/Maven)? No

```
Run gauge -v on your system and paste the results here

Gauge version: 1.0.1
Commit Hash: 4f26566
```

**Comment by BugDiver** [comment]
The actual issue is in `gauge`. Fixing  https://github.com/getgauge/gauge/issues/1152 should fix this.
