### ISSUE TITLE
Gauge plugin errors in intellij

### ISSUE THREAD

**Issue by eabusharkh** [getgauge/Intellij-Plugin#388]
### Expected behavior
I should not get any errors with the gauge plugin.  I recently had an update to intellij and it is currently throwing an error for the gauge plugin (version 0.2.4 is what is available in the marketplace for the gauge plugin).  The error reads: Please log an issue here with the following details and reload the project. //Error: unknown flag: --daemonizeUsage: gauge [flags] [args]

I tried to download and install the most recent version of the plugin, 0.3.15, so when I tried to download it and install the updated gauge jar file manually in intellij, I get the error: "Fail to load plugin descriptor from file gauge-java-0.7.2.jar.  

### Actual behavior
Tell us what happens instead

I get gauge plugin error in intellij.  Intellij puts red lines under my spec scenario steps.

### Steps to reproduce
1. Download the latest update to intellij
2. Launch your gauge project.
3. Get errors.

stacktrace below:
java.lang.RuntimeException: Gauge API not started
	at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:50)
	at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
	at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
	at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
	at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
	at com.thoughtworks.gauge.GaugeConnection.createConnection(GaugeConnection.java:61)
	at com.thoughtworks.gauge.GaugeConnection.<init>(GaugeConnection.java:40)
	at com.thoughtworks.gauge.GaugeModuleComponent.initializeGaugeConnection(GaugeModuleComponent.java:100)
	at com.thoughtworks.gauge.GaugeModuleComponent.createGaugeService(GaugeModuleComponent.java:92)
	at com.thoughtworks.gauge.module.lib.AbstractLibHelper.<init>(AbstractLibHelper.java:37)
	at com.thoughtworks.gauge.module.lib.LibHelperFactory$GaugeModuleLibHelper.<init>(LibHelperFactory.java:43)
	at com.thoughtworks.gauge.module.lib.LibHelperFactory.helperFor(LibHelperFactory.java:33)
	at com.thoughtworks.gauge.GaugeModuleComponent.projectOpened(GaugeModuleComponent.java:66)
	at com.thoughtworks.gauge.GaugeModuleComponent.moduleAdded(GaugeModuleComponent.java:80)
	at com.intellij.openapi.module.impl.ModuleImpl.moduleAdded(ModuleImpl.java:216)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.lambda$fireModuleAddedInWriteAction$4(ModuleManagerImpl.java:649)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:994)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.fireModuleAddedInWriteAction(ModuleManagerImpl.java:647)
	at com.intellij.openapi.module.impl.ModuleManagerComponent.lambda$fireModulesAdded$1(ModuleManagerComponent.java:131)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:82)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:148)
	at com.intellij.openapi.module.impl.ModuleManagerComponent.fireModulesAdded(ModuleManagerComponent.java:131)
	at com.intellij.openapi.module.impl.ModuleManagerImpl.projectOpened(ModuleManagerImpl.java:98)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$fireProjectOpened$18(ProjectManagerImpl.java:822)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:467)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.fireProjectOpened(ProjectManagerImpl.java:817)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$null$5(ProjectManagerImpl.java:397)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransactionAndWait$2(TransactionGuardImpl.java:161)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:82)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:106)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:873)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:461)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:460)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:930)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:205)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:566)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:459)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:82)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:256)
	at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:199)
	at com.intellij.ide.RecentProjectsManagerBase.doOpenProject(RecentProjectsManagerBase.java:508)
	at com.intellij.ide.RecentProjectsManagerBase.doReopenLastProject(RecentProjectsManagerBase.java:636)
	at com.intellij.ide.RecentProjectsManagerBase.reopenLastProjectOnStart(RecentProjectsManagerBase.java:614)
	at com.intellij.idea.IdeaApplication$IdeStarter.lambda$main$1(IdeaApplication.java:404)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:82)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:106)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:115)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:121)
	at com.intellij.idea.IdeaApplication$IdeStarter.main(IdeaApplication.java:400)
	at com.intellij.idea.IdeaApplication.lambda$null$3(IdeaApplication.java:154)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:192)
	at com.intellij.idea.IdeaApplication.lambda$executeInitAppInEdt$5(IdeaApplication.java:154)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:433)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

### Version information

* IntelliJ version and edition(Community/Ultimate): ultimate edition, version 180-161-b12
* OS information: windows 10
* Gauge IntelliJ plugin version: 0.2.4
* Does the project uses any Build tool(Gradle/Maven)? maven
```
Run gauge -v on your system and paste the results here
Gauge version: 1.0.5
Commit Hash: 562f036

Plugins
-------
flash (0.0.1)
html-report (4.0.8)
java (0.7.2)
json-report (0.3.1)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)

**Comment by Apoorva-GA** [comment]
Could you please help us with the IntelliJ version? 
Looking at the error I believe you are on the latest version which is 2019.2. Correct me if I am wrong.

**Comment by eabusharkh** [comment]
That is correct, 2019.2 is the ultimate version that I have of intellij.  The gauge plugin version in the marketplace in intellij has the old version of the plugin, the 2.4, the latest version out there for the plugin is 3.5.

**Comment by Apoorva-GA** [comment]
@eabusharkh Thanks for reporting. We are looking at adding the support to Intellij 2019.2 soon.

**Comment by Apoorva-GA** [comment]
@eabusharkh Fix is available in gauge-intellij-plugin nightly with version >= 26/07/19.
Please fallow the [instructions](https://github.com/getgauge/Intellij-Plugin#installing-nightly) to install the nightly version.
Also we will be releasing the `gauge-Intellij-plugin` with the fix soon.

**Comment by eabusharkh** [comment]
Hi Apoorva-GA, I have tested with intellij 2019.2 and the nightly build listed above and it works now for me.

Thank you!
