### ISSUE TITLE
NullPointerException at CustomRenameHandler.getStepElement

### ISSUE THREAD

**Issue by trung** [getgauge/Intellij-Plugin#406]
### Version information

* IntelliJ version and edition: `Ultimate 2019.2.3` 
* OS information: `MacOS 10.14.6`
* Gauge IntelliJ plugin version: `0.3.17.nightly-2019-07-31`

```
java.lang.NullPointerException
	at com.thoughtworks.gauge.rename.CustomRenameHandler.getStepElement(CustomRenameHandler.java:106)
	at com.thoughtworks.gauge.rename.CustomRenameHandler.isAvailableOnDataContext(CustomRenameHandler.java:58)
	at com.intellij.refactoring.rename.RenameHandlerRegistry.hasAvailableHandler(RenameHandlerRegistry.java:54)
	at com.intellij.refactoring.actions.RenameElementAction.isAvailableOnElementInEditorAndFile(RenameElementAction.java:74)
	at com.intellij.refactoring.actions.BaseRefactoringAction.isAvailableOnElementInEditorAndFile(BaseRefactoringAction.java:62)
	at com.intellij.refactoring.actions.BaseRefactoringAction.update(BaseRefactoringAction.java:182)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:176)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performFastUpdate(ActionUtil.java:129)
	at com.intellij.ui.mac.touchbar.TBItemAnActionButton.updateAnAction(TBItemAnActionButton.java:89)
	at com.intellij.ui.mac.touchbar.TouchBar.lambda$updateActionItems$6(TouchBar.java:250)
	at com.intellij.ui.mac.touchbar.ItemsContainer.lambda$forEachDeep$2(ItemsContainer.java:144)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at com.intellij.ui.mac.touchbar.ItemsContainer.forEachDeep(ItemsContainer.java:139)
	at com.intellij.ui.mac.touchbar.TouchBar.forEachDeep(TouchBar.java:236)
	at com.intellij.ui.mac.touchbar.TouchBar.updateActionItems(TouchBar.java:245)
	at com.intellij.ui.mac.touchbar.TouchBar$UpdateTimerWrapper$1.run(TouchBar.java:300)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.runListenerAction(ActionManagerImpl.java:1492)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.notifyListeners(ActionManagerImpl.java:1481)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.actionPerformed(ActionManagerImpl.java:1465)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:824)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:412)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:411)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by nehashri** [comment]
@trung Can you please add some steps to help reproduce this issue? 
What version of IntelliJ are you using?
What version of Gauge plugin are you using?
Please run `gauge -v` on the command prompt and paste the results here.

**Comment by trung** [comment]
I saw it in the IntelliJ notification panel, not sure why it happened.
```bash
> gauge -v
Gauge version: 1.0.5

Plugins
-------
html-report (4.0.6)
java (0.7.1)
python (0.3.5)
screenshot (0.0.1)
spectacle (0.1.3)
xml-report (0.2.1)
```

You can find other details in the issue description

**Comment by nehashri** [comment]
I have added a commit to handle the null pointer, hopefully you will not see it again.
