### ISSUE TITLE
buildPlugin task fails with memory leak issue

### ISSUE THREAD

**Issue by nehashri** [getgauge/Intellij-Plugin#409]
Running `./gradlew buildPlugin` fails with memory leak issue.
```
2019-11-11 05:36:02,541 [  12657]  ERROR - api.util.objectTree.ObjectTree - Memory leak detected: 'com.thoughtworks.gauge.settings.GaugeConfig@4c028dac' of class com.thoughtworks.gauge.settings.GaugeConfig
See the cause for the corresponding Disposer.register() stacktrace:

java.lang.RuntimeException: Memory leak detected: 'com.thoughtworks.gauge.settings.GaugeConfig@4c028dac' of class com.thoughtworks.gauge.settings.GaugeConfig
See the cause for the corresponding Disposer.register() stacktrace:

	at com.intellij.openapi.util.objectTree.ObjectTree.assertIsEmpty(ObjectTree.java:236)
	at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:149)
	at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:145)
	at com.intellij.openapi.application.impl.ApplicationImpl.disposeSelf(ApplicationImpl.java:234)
	at com.intellij.openapi.application.impl.ApplicationImpl.doExit(ApplicationImpl.java:769)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:744)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:733)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:729)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:696)
	at com.intellij.ide.ui.search.TraverseUIStarter.main(TraverseUIStarter.java:88)
	at com.intellij.idea.IdeaApplication.lambda$null$3(IdeaApplication.java:154)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:192)
	at com.intellij.idea.IdeaApplication.lambda$executeInitAppInEdt$5(IdeaApplication.java:154)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:433)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.Throwable
	at com.intellij.openapi.util.objectTree.ObjectNode.<init>(ObjectNode.java:54)
	at com.intellij.openapi.util.objectTree.ObjectTree.createNodeFor(ObjectTree.java:108)
	at com.intellij.openapi.util.objectTree.ObjectTree.register(ObjectTree.java:72)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:92)
	at com.intellij.openapi.options.SettingsEditor.<init>(SettingsEditor.java:42)
	at com.intellij.openapi.options.SettingsEditor.<init>(SettingsEditor.java:37)
	at com.thoughtworks.gauge.settings.GaugeConfig.<init>(GaugeConfig.java:22)
	at com.thoughtworks.gauge.settings.GaugeSettings.<init>(GaugeSettings.java:11)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:88)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:66)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:48)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:73)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:67)
	at com.intellij.openapi.options.ConfigurableEP$ClassProducer.createElement(ConfigurableEP.java:369)
	at com.intellij.openapi.options.ConfigurableEP.createConfigurable(ConfigurableEP.java:278)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.createConfigurable(ConfigurableWrapper.java:43)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getConfigurable(ConfigurableWrapper.java:108)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.createComponent(ConfigurableWrapper.java:155)
	at com.intellij.ide.ui.search.SearchUtil.processConfigurables(SearchUtil.java:76)
	at com.intellij.ide.ui.search.SearchUtil.processProjectConfigurables(SearchUtil.java:48)
	at com.intellij.ide.ui.search.TraverseUIStarter.startup(TraverseUIStarter.java:106)
	at com.intellij.ide.ui.search.TraverseUIStarter.main(TraverseUIStarter.java:87)
	... 17 more
2019-11-11 05:36:02,542 [  12658]  ERROR - api.util.objectTree.ObjectTree - IntelliJ IDEA 2019.2  Build #IC-192.5728.98 
2019-11-11 05:36:02,542 [  12658]  ERROR - api.util.objectTree.ObjectTree - JDK: 11.0.3; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-11-11 05:36:02,542 [  12658]  ERROR - api.util.objectTree.ObjectTree - OS: Linux 
2019-11-11 05:36:02,542 [  12658]  ERROR - api.util.objectTree.ObjectTree - Plugin to blame: Gauge version: 0.3.17 
```

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed.
Tested version: `946deae`
