### ISSUE TITLE
Internal Ide error: findStepImpl

### ISSUE THREAD

**Issue by ApoorvaM** [getgauge/Intellij-Plugin#42]
Invalid stub element type in index:
file: file:///Users/apoorvam/Downloads/Live_webpage_verifier/Live_webpage_verifier/src/test/java/SportinglifePageChecks.java
psiElement: PsiNameValuePair
requiredClass: interface com.intellij.psi.PsiAnnotation
actualClass: class com.intellij.psi.impl.source.tree.java.PsiNameValuePairImpl
virtualFile: size:3126; stamp:19942; modCount:1425378375000; fileType:JAVA; language:JAVA
document: size:3105; stamp:19945; committed:true; saved:false
psiFile: size:3105; stamp:19945; class:com.intellij.psi.impl.source.PsiJavaFileImpl; language:JAVA
fileAST: size:3105; parsed:true
indexing info: indexed at 1425378375000 with size 3126
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.intellij.psi.stubs.StubIndexImpl.reportStubPsiMismatch(StubIndexImpl.java:513)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:155)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
	at com.intellij.psi.impl.java.stubs.index.JavaAnnotationIndex.get(JavaAnnotationIndex.java:48)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher$4.compute(AnnotatedElementsSearcher.java:98)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher$4.compute(AnnotatedElementsSearcher.java:94)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:917)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher.a(AnnotatedElementsSearcher.java:94)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher.execute(AnnotatedElementsSearcher.java:62)
	at com.intellij.psi.impl.search.AnnotatedElementsSearcher.execute(AnnotatedElementsSearcher.java:38)
	at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:43)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
	at com.intellij.util.AbstractQuery.findAll(AbstractQuery.java:37)
	at com.intellij.util.InstanceofQuery.findAll(InstanceofQuery.java:38)
	at com.thoughtworks.gauge.util.StepUtil.getStepMethods(StepUtil.java:154)
	at com.thoughtworks.gauge.util.StepUtil.findStepImpl(StepUtil.java:50)
	at com.thoughtworks.gauge.reference.StepReference.resolve(StepReference.java:42)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferenceOrReferencedElement(TargetElementUtilBase.java:315)
	at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:95)
	at com.intellij.codeInsight.TargetElementUtilBase.findTargetElement(TargetElementUtilBase.java:200)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:60)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:88)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1143)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:281)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

**Comment by ApoorvaM** [comment]
Unable to reproduce. Hence closing.
