### ISSUE TITLE
Gauge plugin 0.3.18 cannot be used in IntelliJ Idea Ultimate 2019.3 on mac os

### ISSUE THREAD

**Issue by AlexBasescu** [getgauge/Intellij-Plugin#422]
### Expected behavior
I should be able to run .spec files without issues.

### Actual behavior
When trying to run a .spec file, during compilation I receive the following error inside Intellij:
`java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.execution.process.ProcessHandler$2.invoke(ProcessHandler.java:214)
	at com.sun.proxy.$Proxy31.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:188)
	at com.intellij.execution.process.ColoredProcessHandler.coloredTextAvailable(ColoredProcessHandler.java:54)
	at com.intellij.execution.process.AnsiEscapeDecoder.processTextChunk(AnsiEscapeDecoder.java:99)
	at com.intellij.execution.process.AnsiEscapeDecoder.escapeText(AnsiEscapeDecoder.java:63)
	at com.intellij.execution.process.ColoredProcessHandler.notifyTextAvailable(ColoredProcessHandler.java:43)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:171)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:209)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:193)
	at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:105)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:67)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:160)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.io.BaseDataReader.lambda$start$0(BaseDataReader.java:50)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 2 column 1 path $.message
	at com.google.gson.Gson.fromJson(Gson.java:942)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at com.google.gson.Gson.fromJson(Gson.java:813)
	at com.thoughtworks.gauge.execution.runner.GaugeOutputToGeneralTestEventsProcessor.processServiceMessages(GaugeOutputToGeneralTestEventsProcessor.java:61)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.processConsistentText(OutputToGeneralTestEventsConverter.java:113)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter$1.onTextAvailable(OutputToGeneralTestEventsConverter.java:69)
	at com.intellij.execution.testframework.sm.runner.OutputEventSplitter.flushInternal(OutputEventSplitter.kt:166)
	at com.intellij.execution.testframework.sm.runner.OutputEventSplitter.flushInternal$default(OutputEventSplitter.kt:151)
	at com.intellij.execution.testframework.sm.runner.OutputEventSplitter.processInternal(OutputEventSplitter.kt:98)
	at com.intellij.execution.testframework.sm.runner.OutputEventSplitter.process(OutputEventSplitter.kt:72)
	at com.intellij.execution.testframework.sm.runner.OutputToGeneralTestEventsConverter.process(OutputToGeneralTestEventsConverter.java:95)
	at com.intellij.execution.testframework.sm.SMTestRunnerConnectionUtil$2.onTextAvailable(SMTestRunnerConnectionUtil.java:214)
	... 23 more
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 2 column 1 path $.message
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1031)
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	... 35 more`
### Version information

* IntelliJ version and edition(Community/Ultimate): Ultimate Edition 2019.3
* OS information: MacOS Catalina 10.15.1
* Gauge IntelliJ plugin version: 0.3.18
* Does the project uses any Build tool(Gradle/Maven)?
  Yes, maven.
* Run gauge -v on your system and paste the results here
`Gauge version: 1.0.6

Plugins
-------
html-report (4.0.8)
java (0.7.3)
screenshot (0.0.1)
xml-report (0.2.2)`

**Comment by shubhamsc** [comment]
@AlexBasescu I'm not seeing any error with IntelliJ idea 2019.3 and gauge 0.3.18.
Are you getting the same error with gauge java_maven sample project?
Create a sample project with `gauge init java_maven` and run in IntelliJ Idea.

**Comment by AlexBasescu** [comment]
@shubhamsc I'm sorry, it was a mistake from my side. Actually I had an access right problems for the project I'm involved in, not a problem with the plugin and intellij.
