### ISSUE TITLE
MacOS - java.util.MissingFormatArgumentException: Format specifier '%s'

### ISSUE THREAD

**Issue by sudhindra-aithal** [getgauge/Intellij-Plugin#428]
Format specifier '%s'
java.util.MissingFormatArgumentException: Format specifier '%s'
	at java.base/java.util.Formatter.format(Formatter.java:2672)
	at java.base/java.util.Formatter.format(Formatter.java:2609)
	at java.base/java.lang.String.format(String.java:3274)
	at com.thoughtworks.gauge.connection.GaugeConnector.connect(GaugeConnector.java:45)
	at com.thoughtworks.gauge.connection.GaugeConnector.makeConnectionsToGaugeCore(GaugeConnector.java:35)
	at com.thoughtworks.gauge.GaugeRuntime.makeConnection(GaugeRuntime.java:120)
	at com.thoughtworks.gauge.GaugeRuntime.connectSynchronously(GaugeRuntime.java:106)
	at com.thoughtworks.gauge.GaugeRuntime.startGaugeServer(GaugeRuntime.java:76)
	at com.thoughtworks.gauge.GaugeRuntime.main(GaugeRuntime.java:53)

### Expected behavior
Gauge should work fine

### Actual behavior
Gauge is not starting

### Steps to reproduce
Try running script

### Version information

* IntelliJ version and edition(Community/Ultimate): Community 2019.3
* OS information: Mac OS 10.15.3
* Gauge IntelliJ plugin version: 
* Does the project uses any Build tool(Gradle/Maven)? Maven
```
Run gauge -v on your system and paste the results here
```
Gauge version: 1.0.7
Plugins
-------
html-report (4.0.9)
java (0.7.4)
screenshot (0.0.1)

**Comment by sudhindra-aithal** [comment]
Upgrading version in java and pom file, fixed the issue
