### ISSUE TITLE
Exception occurred in Gauge plugin [IntelliJ Idea]

### ISSUE THREAD

**Issue by daniele-pintus** [getgauge/Intellij-Plugin#437]
#### gauge process exited with code 2

* OS: Windows 10
* Idea version: 2020.1.1 (community)
* API version: IC-201.7223.91
* Plugin version: 0.3.20
* Gauge version: 1.0.6 (with Windows installer)

step to reproduce: Exception occurs at startup. 
Moreover, after installing the Gauge plugin, IntelliJ startup is very very slow, frozen for several minutes. then the gauge plugin is not even loaded properly and I have to restart again :(

```
panic: assignment to entry in nil map

goroutine 8 [running]:
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).addToStepsCache(...)
	/Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:257
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).OnConceptFileModify(0xc00018c000, 0xc00023c2d0, 0x44)
	/Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:363 +0x66c
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).onFileModify(0xc00018c000, 0xc000056080, 0xc00023c2d0, 0x44)
	/Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:402 +0xb6
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).handleEvent(0xc00018c000, 0xc0001c4230, 0x44, 0x2, 0xc000056080)
	/Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:433 +0x1af
github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).watchForFileChanges.func1(0xc000056080, 0xc00018c000)
	/Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:456 +0x18a
created by github.com/getgauge/gauge/api/infoGatherer.(*SpecInfoGatherer).watchForFileChanges
	/Users/admin/Documents/Doga/pipelines/Gauge-Build/src/github.com/getgauge/gauge/api/infoGatherer/specDetails.go:452 +0x155

**Comment by negiDharmendra** [comment]
@daniele-pintus Please create a sample project `gauge init java` and see if you are facing the same issue. If not then we will require a sample project to reproduce this issue. 

**Note:** Please upgrade Gauge to the [latest](https://github.com/getgauge/gauge/releases/latest) version

**Comment by NivedhaSenthil** [comment]
Closing due to inactivity, feel free to reopen if you still facing issue with the latest version.
