### ISSUE TITLE
Internal IDE err : getStepValue

### ISSUE THREAD

**Issue by ApoorvaM** [getgauge/Intellij-Plugin#44]
Exception : 
null
java.lang.NullPointerException
	at java.util.Hashtable.get(Hashtable.java:334)
	at com.thoughtworks.gauge.core.Gauge.getGaugeService(Gauge.java:32)
	at com.thoughtworks.gauge.language.psi.SpecPsiImplUtil.getStepValue(SpecPsiImplUtil.java:44)
	at com.thoughtworks.gauge.language.psi.impl.SpecStepImpl.getStepValue(SpecStepImpl.java:37)
	at com.thoughtworks.gauge.util.StepUtil.filter(StepUtil.java:96)
	at com.thoughtworks.gauge.util.StepUtil.findStepImpl(StepUtil.java:51)
	at com.thoughtworks.gauge.reference.StepReference.resolve(StepReference.java:39)
	at com.intellij.internal.psiView.PsiViewerDialog.a(PsiViewerDialog.java:1050)
	at com.intellij.internal.psiView.PsiViewerDialog.access$200(PsiViewerDialog.java:102)
	at com.intellij.internal.psiView.PsiViewerDialog$2.getListCellRendererComponent(PsiViewerDialog.java:275)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:34)
	at javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1344)
	at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1294)
	at javax.swing.plaf.basic.BasicListUI.paintImpl(BasicListUI.java:246)
	at javax.swing.plaf.basic.BasicListUI.paint(BasicListUI.java:222)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:153)
	at javax.swing.JComponent.paintComponent(JComponent.java:760)
	at com.intellij.ui.components.JBList.paintComponent(JBList.java:146)
	at javax.swing.JComponent.paint(JComponent.java:1037)
	at com.intellij.ui.components.JBList.paint(JBList.java:100)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5106)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4890)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:814)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:802)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:802)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:745)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:725)
	at javax.swing.RepaintManager.access$1000(RepaintManager.java:46)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1680)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by prateekbaheti** [comment]
Same as #50. Closing
