### ISSUE TITLE
Unable to debug using IntelliJ cause of exception "unable to open debugger port : java.net.ConnectException - Connection refused: connect"

### ISSUE THREAD

**Issue by RajatNair** [getgauge/Intellij-Plugin#442]
### Describe the bug
> Error running '': Unable to open debugger port : java.net.ConnectException "Connection refused: connect"

Seeing this exception with IntelliJ Ultimate edition when I try to debug a spec using Gauge's IntelliJ plugin -
![image](https://user-images.githubusercontent.com/3319907/87934806-70de6f00-caad-11ea-984c-53ea0bb551b4.png)

The only way I can debug is setting `GAUGE_DEBUG_OPTS=<port>` and then using IntelliJ's remote debugging configuration template. But it's valid only for single spec run. Have to re-do these steps for each spec run.

#### Gauge (Output of `gauge -v`)
```Json
{
    "version": "1.0.8",
    "commitHash": "28617ea",
    "plugins": [
        {
            "name": "csharp",
            "version": "0.10.6"
        },
        {
            "name": "html-report",
            "version": "4.0.12"
        },
        {
            "name": "java",
            "version": "0.7.8"
        },
        {
            "name": "js",
            "version": "2.3.12"
        },
        {
            "name": "python",
            "version": "0.3.10"
        },
        {
            "name": "ruby",
            "version": "0.5.3"
        },
        {
            "name": "screenshot",
            "version": "0.0.1"
        },
        {
            "name": "spectacle",
            "version": "0.1.4"
        },
        {
            "name": "xml-report",
            "version": "0.2.3"
        }
    ]
}
```

#### Node.js/Java/Python/.Net/Ruby version
OpenJDK 11

#### Operating System information
Windows 10

#### IDE information
IntelliJ Ultimate 2020.1.3

**Comment by donRumata83** [comment]
@sriv This issue is quite critical for us. We want to update our gauge to 1.1.1 because of this https://github.com/getgauge/gauge/issues/1633.  But I couldn't upgrade because I can't leave all team without debugging option. Could you please provide some help from your side or give some insights about where we have to look for fixes.

**Comment by Sshviq** [comment]
Hi, I've faced with the same issue like donRumata83; 

-------
html-report (4.0.8)
java (0.7.4)
reportportal (1.0.1)
screenshot (0.0.1)
xml-report (0.2.1)

**Comment by sriv** [comment]
hi @donRumata83 - I cannot see this issue when I try to troubleshoot with my Intellij IDEA Community version. I am able to put breakpoints in my java code, and when I debug the spec, I can see the debugger waiting at the breakpoints.

Before you start debugging, ensure that you are on [latest versoin](https://github.com/getgauge/Intellij-Plugin/releases/latest) of the plugin and can replicate the issue.

Some pointers where you can start looking deeper:

##### Setup a development environment:

- https://github.com/getgauge/intellij-plugin/wiki#steps

##### Building the plugin from source:

- https://github.com/getgauge/intellij-plugin#building-from-source

Once you have the code and setup, for this issue I'd start looking at [`GaugeDebugInfo`]() class. This class' instance is created when a spec/scenario is launched via a `Debug` run configuration.

The debugger is quite simple - it creates sets `GAUGE_DEBUG_OPTS` port environment automatically for every run. This environment variable is passed to `gauge-java` which sets it as an argument to the jvm process. 

https://github.com/getgauge/gauge-java/blob/master/gauge-java.go#L33 - the args passed to java process.

I believe gauge-java is listening to the debugger ok, but the Intellij plugin isn't able to connect to it. You can try logging the port that it was trying to use and try setting the port explicitly, and attach IDEA's debugger explicitly to ensure that debugging on that port works ok.

The port is set by the plugin by [scanning for a free port](https://github.com/getgauge/Intellij-Plugin/blob/master/src/com/thoughtworks/gauge/execution/GaugeDebugInfo.java#L49), however you may see if you want to make this configurable. 

Hope this helps in getting started, feel free to ask if you have any more questions.

**Comment by sriv** [comment]
Please note that if we knew the problem, we would fix it (despite the fact that this is deprecated). Unfortunately, the issue isn't replicable in our projects. 

If you have any hints on how we can replicate this, we may perhaps be able to be more specific in possible ways to solve this, or even fix it if it's not a lot of work!

**Comment by olejkavn** [comment]
@sriv  for my case it's huge project:
gauge config runner_request_timeout 500000
gauge config runner_connection_timeout 500000

without such config my project doesn't work at all. So looks like there are some misconfiguration between IDEA plugin and gauge

**Comment by sriv** [comment]
Looking at https://github.com/getgauge/gauge-java/blob/master/gauge-java.go#L33, gauge-java's debugger has a hard coded timeout for 25 seconds. This should ideally be >= `runner_connection_timeout` 

I've created a pull request in gauge-java - https://github.com/getgauge/gauge-java/pull/472

This should let you set `GAUGE_DEBUG_CONNECTION_TIMEOUT` to a value other than the default 25000ms.

@olejkavn would you be able to install from source and verify?

On a sidenote - with gauge-java 0.7.9, do you still need such high values for `runner_request_timeout` and `runner_connection_timeout` ?

**Comment by olejkavn** [comment]
@sriv  with 0.7.9 I don't need, but I need refactor my project :). So I should do it step by step:
1. migrate to new version of gauge
2. do refactoring

I've already tried to build it from project, and still have red project, so it would be great if you will share it in zip)
olejkavn@gmail.com

**Comment by sriv** [comment]
@olejkavn the build artifacts are here: https://github.com/getgauge/gauge-java/suites/950026995/artifacts/11840292

Note that the zip file contains buils for all OS/Arch. Please select the version that matches your OS/Arch.

You will need to do `gauge uninstall java --version 0.7.9` and then run `gauge install java -f <path_to_zip>`

**Comment by donRumata83** [comment]
@sriv I'll test it in a couple of minutes.

**Comment by sriv** [comment]
thanks @donRumata83 - please try increasing the `GAUGE_DEBUG_CONNECTION_TIMEOUT` to a higher value and see if it helps.

**Comment by donRumata83** [comment]
@sriv I've set up the new parameter GAUGE_DEBUG_CONNECTION_TIMEOUT 200000

Runner Ready for Debugging
Listening for transport dt_socket at address: 57366
ERROR: transport error 203: timed out waiting for connection
JDWP exit error JVMTI_ERROR_NONE(0): could not connect, timeout or fatal error [:362]
Error ----------------------------------

[Gauge]
Panicing : runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0xc000139218, 0x1682d80, 0x1cd69b0)
	/usr/local/Cellar/go/1.14.4/libexec/src/runtime/debug/stack.go:24 +0x9d
main.recoverPanic()
	/private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/gauge.go:27 +0x57
panic(0x1682d80, 0x1cd69b0)
	/usr/local/Cellar/go/1.14.4/libexec/src/runtime/panic.go:969 +0x166
github.com/getgauge/gauge/runner.(*GrpcRunner).ExecuteMessageWithTimeout(0x0, 0xc0000d02c0, 0xc0005bf400, 0xc0005ac0c0, 0x0)
	/private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/runner/grpcRunner.go:195 +0x22
github.com/getgauge/gauge/validation.(*SpecValidator).validateStep(0xc0005ac000, 0xc0003c6500, 0xc0003213e0, 0x28)
	/private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/validation/validate.go:345 +0x19e
github.com/getgauge/gauge/validation.(*SpecValidator).Step(0xc0005ac000, 0xc0003c6500)
	/private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/validation/validate.go:313 +0x5f1
github.com/getgauge/gauge/validation.(*SpecValidator).Step(0xc0005ac000, 0xc0001ff200)
	/private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/validation/validate.go:307 +0x78
github.com/getgauge/gauge/gauge.(*Specification).Traverse(0xc0003ad600, 0x185c140, 0xc0005ac000, 0xc000139960)
	/private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/gauge/specification.go:261 +0x256
github.com/getgauge/gauge/validation.(*SpecValidator).validate(0xc0005ac000, 0xc0005ac000, 0x13, 0x0)
	/private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/validation/validate.go:298 +0x8d
github.com/getgauge/gauge/validation.(*validator).Validate(0xc0005bfb08, 0x185ba80)
	/private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/validation/validate.go:284 +0x115
github.com/getgauge/gauge/validation.ValidateSpecs(0xc00007eb00, 0x1, 0x4, 0x0, 0x0)
	/private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/validation/validate.go:174 +0x227
github.com/getgauge/gauge/execution.glob..func1(0xc00007eb00, 0x1, 0x4, 0x0)
	/private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/execution/execute.go:107 +0x10a
github.com/getgauge/gauge/cmd.execute(0x1ce07c0, 0xc00007eb00, 0x1, 0x4)
	/private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/cmd/run.go:244 +0x241
github.com/getgauge/gauge/cmd.glob..func13(0x1ce07c0, 0xc00007eb00, 0x1, 0x4)
	/private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/cmd/run.go:93 +0x27c
github.com/spf13/cobra.(*Command).execute(0x1ce07c0, 0xc00007eac0, 0x4, 0x4, 0x1ce07c0, 0xc00007eac0)
	/private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/vendor/github.com/spf13/cobra/command.go:833 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x1ce1440, 0x1c95800, 0xc000000180, 0xc0001d9f78)
	/private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/vendor/github.com/spf13/cobra/command.go:917 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/vendor/github.com/spf13/cobra/command.go:867
github.com/getgauge/gauge/cmd.Parse(0x0, 0x0)
	/private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/cmd/cmd.go:111 +0x3d
main.main()
	/private/tmp/gauge-20200704-29582-ed3o73/gauge-1.1.1/gauge.go:19 +0x48

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://spectrum.chat/gauge

Your Environment Information -----------
	darwin, 1.1.1
	html-report (4.0.12), java (0.7.9), reportportal (1.7.0), screenshot (0.0.1), xml-report (0.2.3)

Process finished with exit code 1

**Comment by sriv** [comment]
@donRumata83 this tells me that Intellij IDEA's debugger could not attach to gauge-java process. 

At this point couple of things to try:

- try debugging the same project with Visual Studio Code (install gauge and java extensions). If this works, then we know there's something wrong/missing in the intellij plugin.

- try attaching the Intellij debugger manually
    - open the project in Intellij IDEA, do not execute.
    - run the project via terminal, set `GAUGE_DEBUG_OPTS=<port>` where `port` can be any free port in your machine. _You could use `57366`, just to check if manually attaching the debugger works for the same port that failed above_
    - wait for `Runner Ready for Debugging` to be printed.
    - Now in IDEA, choose `Run -> Attach To Process` and you should see the gauge-java process listed. Choose and see if the breakpoints are hit.

If one or both of the above options work, then it would mean Intellij-Plugin's got a bug.

**Comment by donRumata83** [comment]
@sriv The second way works for me. The runner hit the breakpoint.

**Comment by sriv** [comment]
Thanks @donRumata83 I'll look deeper into gauge-Java.

**Comment by sriv** [comment]
Another quick check - if you are using maven/gradle can you ensure that the gauge-java dependency is updated?

**Comment by donRumata83** [comment]
@sriv You talking about dependency in pom file? Yes, the dependency is updated and after you'd released a new version of 0.7.9 I manually delete the old library from m2 and reimport a new one.

**Comment by donRumata83** [comment]
Hi, @sriv, I want to try to find the bug in the plugin in my free time. Could somebody help me with way where I have to start?  How I can debug work of this plugin etc.

**Comment by sriv** [comment]
hi @donRumata83 - does [my earlier] comment(https://github.com/getgauge/Intellij-Plugin/issues/442#issuecomment-662388300) help get started?

**Comment by donRumata83** [comment]
@sriv Yes, I'll start from this. Actually I've missed that comment.

**Comment by jreznot** [comment]
> Hi, @sriv, I want to try to find the bug in the plugin in my free time. Could somebody help me with way where I have to start? How I can debug work of this plugin etc.

I can help. Right now we are trying to solve this and maintain a plugin inside IntelliJ IDEA Community repository
